<?php 
require_once("c_config.php"); 
if(isset($_POST['c_btn'])){ 
  header("location:c_login.php");
}
if(isset($_POST['s_btn'])){ 
    header("location:c_login.php");
}
  if(isset($_POST['a_btn'])){ 
    header("location:c_login.php");
}
?>